cursor #cecb56
cursor_text_color #333200

url_color #cbc8a4

active_border_color #cecb56
inactive_border_color #474747
bell_border_color #ffb4ab
visual_bell_color none

active_tab_background #cecb56
active_tab_foreground #333200
inactive_tab_background #474747
inactive_tab_foreground #c6c6c6
tab_bar_background #131313
tab_bar_margin_color none

normal_white #e2e2e2
normal_black #131313
normal_red #ffb4ab
normal_yellow #a4d0bc
normal_green #cbc8a4
normal_cyan #cecb56
normal_blue #cecb56
normal_magenta #cbc8a4

bright_white #e2e2e2
bright_black #474747
bright_red #ffb4ab
bright_yellow #a4d0bc
bright_green #cbc8a4
bright_cyan #cecb56
bright_blue #cecb56
bright_magenta #cbc8a4

selection_foreground #323218
selection_background #cbc8a4

background #131313
foreground #e2e2e2
